version: 2
jobs:
  build:
    docker: #  tircleci/node:10.0.0 # the primary container, where your job's commands are run
        - image: circleci/node:10.0.0  # run in the background
    steps:
<<<<<<< Updated upstream
      - checkout # check out the code in the project directory
      - run: npm install 
      - run: npm start & 
      - run: npm test 
      - deploy:
          name: digital-ocean
          command: ssh -o "StrictHostKeyChecking no" root@167.71.166.254"cd ~/circleciexpress; git pull; npm install; npm start &"
  
=======
    - run:
        command: welcome_message.sh
        name: Congratulations!
    - run:
        command: next_steps.sh
        name: Next Steps
    - run:
        command: examples.sh
        name: 'Help Topic: Examples - Tutorials, Sample Configs, Cookbook'
    - run:
        command: concepts.sh
        name: 'Help Topic: Overview and Concepts'
    - run:
        command: using_the_cli.sh
        name: 'Help Topic: Using the CLI'
workflows:
  welcome:
    jobs:
    - welcome/run
  version: 2

# Original config.yml file:
# # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
# # Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
# workflows:
#   # Name the workflow \"welcome\"
#   welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run
>>>>>>> Stashed changes
